name: Deploy gh-pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Push to another branch
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git checkout -b gh-pages
        git add .
        git commit -m "Auto push to gh-pages branch"
        git push -u origin gh-pages