name: Deploy gh-pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Configure Git User
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"

    - name: Push to gh-pages
      run: |
        git checkout -b gh-pages
        git push -f origin gh-pages
